pipeline {
    agent {
        docker { 
            image 'node:16-alpine' 
            args '--user root' // Allow Docker container to run as root for installing packages
        }
    }
    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }
        stage('Install Java') {
            steps {
                script {
                    sh '''
                        apk update
                        apk add openjdk11
                    '''
                }
            }
        }
        stage('Create HelloWorld.java') {
            steps {
                script {
                    sh '''
                        echo "public class HelloWorld {
                            public static void main(String[] args) {
                                System.out.println("Hello, World!");
                            }
                        }" > HelloWorld.java
                    '''
                }
            }
        }
        stage('Compile Java') {
            steps {
                script {
                    sh 'javac HelloWorld.java'
                }
            }
        }
        stage('Run Java Program') {
            steps {
                script {
                    sh 'java HelloWorld'
                }
            }
        }
    }
}
