pipeline {
    agent {
        docker { image 'node:16-alpine' }
    }
    stages {
        stage('Test Node Version') {
            steps {
                sh 'node --version'
            }
        }
        stage('Create HelloWorld.java') {
            steps {
                script {
                    // Create the HelloWorld.java file dynamically
                    writeFile file: 'HelloWorld.java', text: '''
public class HelloWorld {
    public static void main(String[] args) {
        // Prints "Hello, World!" to the console
        System.out.println("Hello, World!");
    }
}
'''
                }
            }
        }
        stage('Compile Java') {
            steps {
                script {
                    // Compile the HelloWorld.java file using the existing JDK
                    sh 'javac HelloWorld.java'
                }
            }
        }
        stage('Run Java Program') {
            steps {
                script {
                    // Run the compiled HelloWorld class
                    sh 'java HelloWorld'
                }
            }
        }
    }
    post {
        success {
            echo 'The Java program ran successfully!'
        }
        failure {
            echo 'The Java program failed to run.'
        }
    }
}

